baseURL: https://www.danielssilva.dev

title: "Daniel Silva"

# Manage languages
# For any more details, you can check the official documentation: https://gohugo.io/content-management/multilingual/
languages:
  en:
    locale: en-US
    label: English
    weight: 1

# Control TOC depth
markup:
  tableOfContents:
    startLevel: 2
    endLevel: 6
    ordered: false

# Enable global emoji support
enableEmoji: true

# Site parameters
params:
  # GitHub repo URL of your site
  gitRepo: https://github.com/DanielSSilva/DanielSSilva.github.io

  # specify whether you want to write some blog posts or not
  enableBlogPost: false
  logo:
    favicon: "images/favicon.png"

